### ISSUE TITLE
fit_litter could return warning when parameters fit on the bounds

### ISSUE THREAD

**Issue by j-tweed** [cornwell-lab-unsw/litterfitter#11]
I think it would be useful for users to be warned when one or more of the best fit parameters are equal to their respective upper or lower bound. That also implies that users should be able to supply alternative bounds... but that is a bit trickier.

**Comment by wcornwell** [comment]
Looked at this and it seems pretty hard.  Any ideas for an approach?

**Comment by j-tweed** [comment]
I have an idea, will try later today
