### ISSUE TITLE
steady state function for cont.quality.1 

### ISSUE THREAD

**Issue by wcornwell** [cornwell-lab-unsw/litterfitter#15]
is this around somewhere?

**Comment by j-tweed** [comment]
looking back over the reviews and our responses, I see that cont.quality.2 is just a reparameterization of cont.quality.1. Also the latter seems to have less desirable properties for fitting (often fits on the boundary).

Is there any strong need to keep both? I think cont.quality.2 seems to behave better...

**Comment by wcornwell** [comment]
Yeah, let's drop cont.quality.1, simpler....

**Comment by wcornwell** [comment]
possibly resolved see 21fd63d8bd9e0e2951183caae070ad25ad60fcda
