### ISSUE TITLE
some issues with boundary fits and discrete pool models

### ISSUE THREAD

**Issue by wcornwell** [cornwell-lab-unsw/litterfitter#17]
check out:

```R
model <- "discrete.parallel"
data(pineneedles)
fit <- fit_litter(time = pineneedles$Year, mass.remaining = pineneedles$Mass.remaining,
                    model = model, iters = 2000)

model <- "discrete.series"
fit <- fit_litter(time = pineneedles$Year, mass.remaining = pineneedles$Mass.remaining,
                    model = model, iters = 2000)
```

Might have to change the limits?

**Comment by j-tweed** [comment]
I think in cases where a single pool model fits well, then the two-pool models will always give fits with the proportioning parameter on one of the bounds (effectively making the two pool model into a one pool model). I don't think this is a problem, but maybe the fact that it throws a warning might create unnecessary confusion... ?

**Comment by wcornwell** [comment]
Yeah you're right.

Still probably good to throw the warning.  I have to adjust the tests I wrote.  I forgot how unstable those two models are.
