### ISSUE TITLE
Add example dataset

### ISSUE THREAD

**Issue by wcornwell** [cornwell-lab-unsw/litterFitter#2]
Figure out how to add data to an R package

**Comment by wcornwell** [comment]
@j-tweed do you know how to do this?

**Comment by j-tweed** [comment]
as a test I added the Pinus strobus hobbie M8 dataset from ArtDeco... should be accessible as `pineleaves` - can you confirm this works @wcornwell ?

**Comment by wcornwell** [comment]
works!  :clap:
