### ISSUE TITLE
Fit_litter function error

### ISSUE THREAD

**Issue by sbperez** [cornwell-lab-unsw/litterfitter#23]
Issue with running `fit_litter` function for some species in wood decay dataset. Example: 

```
library(litterfitter)
fit<-fit_litter(time=c(18, 22, 21, 15, 25, 10, 10,  0),
                mass.remaining=c(0.9869, 0.8659, 1.0127, 0.4911, 0.4608, 0.9807, 0.8721, 1.0000),
                model=c("neg.exp"),iters=500)
summary(fit)

Summary of litFit object
Model type: neg.exp 
Number of observations:  8 
Parameter fits: 0.0125 
Error in signif(x$time_to_50, 3) : 
  non-numeric argument to mathematical function
```

Any help or thoughts would be greatly appreciated!

**Comment by wcornwell** [comment]
Thanks for posting here @sbperez !  

I think the problem is that the summary is trying to calculate Time to 50% mass loss and that value is outside of the range of the data.  It should return a warning, but instead it's giving an error.  Will see if I can get it to return something sensible for that case.

**Comment by wcornwell** [comment]
```{r}
> library(litterfitter)
> fit<-fit_litter(time=c(18, 22, 21, 15, 25, 10, 10,  0),
+                 mass.remaining=c(0.9869, 0.8659, 1.0127, 0.4911, 0.4608, 0.9807, 0.8721, 1.0000),
+                 model=c("neg.exp"),iters=500)
Number of successful fits:  474  out of 500 
> summary(fit)
Summary of litFit object
Model type: neg.exp 
Number of observations:  8 
Parameter fits: 0.0125 
Time to 50% mass loss: 55.6 
Implied steady state litter mass: 80.2 in units of yearly input 
AIC:  -1.4739 
AICc:  -0.8072 
BIC:  -1.3944 
Warning message:
In time_to_prop_mass_remaining(object, 0.5) :
  Not predicted to reach threshold mass (usu 50% loss) within the time range of the data.
```
Does this behavior work for you?

**Comment by liuguofang** [comment]
Hi Will,
      How are you? 
      I run the code. The output was as follows: 

Summary of litFit object
Model type: neg.exp 
Number of observations:  8 
Parameter fits: 0.0125 
Error in signif(x$time_to_50, 3) : 
  non-numeric argument to mathematical function




liuguofang2004@126.com
 
From: Will Cornwell
Date: 2020-02-11 10:44
To: cornwell-lab-unsw/litterfitter
CC: Subscribed
Subject: Re: [cornwell-lab-unsw/litterfitter] Fit_litter function error (#23)
> library(litterfitter)
> fit<-fit_litter(time=c(18, 22, 21, 15, 25, 10, 10,  0),
+                 mass.remaining=c(0.9869, 0.8659, 1.0127, 0.4911, 0.4608, 0.9807, 0.8721, 1.0000),
+                 model=c("neg.exp"),iters=500)
Number of successful fits:  474  out of 500 
> summary(fit)
Summary of litFit object
Model type: neg.exp 
Number of observations:  8 
Parameter fits: 0.0125 
Time to 50% mass loss: 55.6 
Implied steady state litter mass: 80.2 in units of yearly input 
AIC:  -1.4739 
AICc:  -0.8072 
BIC:  -1.3944 
Warning message:
In time_to_prop_mass_remaining(object, 0.5) :
  Not predicted to reach threshold mass (usu 50% loss) within the time range of the data.

Does this behavior work for you?

**Comment by wcornwell** [comment]
hi @liuguofang !  Maybe try to install from github again?  I just pushed a new version

**Comment by sbperez** [comment]
@wcornwell thanks so much for your help! It now runs without a problem. @liuguofang I had to restart r after reinstalling the package to get it to run correctly.

**Comment by wcornwell** [comment]
Thanks @sbperez !
