### ISSUE TITLE
accessing ?litterFitter

### ISSUE THREAD

**Issue by j-tweed** [cornwell-lab-unsw/litterfitter#6]
`?litterFitter` goes to the help file of the whole package not the documentation for `litterFitter()` as function.

Only noticed this because I couldn't get `example(litterFitter)` to work.

Any idea how to solve this?

**Comment by wcornwell** [comment]
There is a bunch of things about package documentation I don't totally understand.  I'm hoping #5 will solve this.

**Comment by wcornwell** [comment]
Also, it probably wasn't a great idea to have the package and the main function have the same name. I like `litterFitter` as the package name.  Maybe change the function to `fitLitter`?

**Comment by wcornwell** [comment]
Linked to #5 and #8.  but now resolved.
