### ISSUE TITLE
naming issue: capitalization in R package and function names

### ISSUE THREAD

**Issue by wcornwell** [cornwell-lab-unsw/litterfitter#8]
I have some collaborators who have been arguing for all lower case all the time, with `_` separating words when necessary.  This is what `ggplot2` and `dplyr` do (mostly), and might be more modern style. Also avoids some of the chaotic naming of packages like `data.table`

If we go with that it could be:

`litterfitter` as the package and 
`fit_litter` as the main function
and `litfit` as the object

function could also be `fitlitter` i suppose.  

Any thoughts @j-tweed ?

**Comment by j-tweed** [comment]
I like it. With a slight preference for `fit_litter()` as the main function. I guess it might take a bit of grepping to find and replace all the instances. I will try and get to it when I have some time on a train.

**Comment by wcornwell** [comment]
OK cool.  will switch things around
